# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: raygesualdo.com
subtitle:
description:
author: Ray Gesualdo
language: en
timezone: America/New_York

# URL
url: http://raygesualdo.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: topics
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: iosta

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:

# Markdown options
# marked:

# Sass options
node_sass:
  # outputStyle: compressed
  # sourceComments: false

# Social media
sm:
  twitter:
    link: https://twitter.com/RayGesualdo
  github:
    link: https://github.com/raygesualdo
  linkedin:
    link: https://www.linkedin.com/in/raygesualdo

# Feed
feed:
  type: rss2
  path: feed.xml
  limit: 20
