import { GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'
import {
  getCategories,
  getCategoryBySlug,
  Category,
} from '../../lib/categories'
import { getAllPosts, PostData } from '../../lib/posts'

type CategoryProps = {
  category: Category
  data: PostData[]
}

export default function CategoryIndex({ category, data }: CategoryProps) {
  return (
    <div>
      <Head>
        <title>RayGesualdo.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Category: {category.name}</h1>

      {data.map((post) => {
        const { year, month, day, slug } = post

        return (
          <div key={slug}>
            <h2>
              <a href={`/posts/${year}/${month}/${day}/${slug}`}>
                {post.title}
              </a>
            </h2>
            <small>
              {post.date} | {Math.ceil(post.readingTime?.minutes)} Minute Read
            </small>{' '}
            <p>{post.excerpt}</p>
          </div>
        )
      })}
    </div>
  )
}

export const getStaticProps: GetStaticProps<CategoryProps> = async (
  context
) => {
  const category = getCategoryBySlug((context.params?.slug as string) ?? '')!
  const allPosts = await getAllPosts()
  const data = allPosts
    .filter((post) => post.category?.slug === category.slug)
    .reverse()
  return {
    props: {
      category,
      data,
    },
  }
}

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = getCategories().map(({ slug }) => ({ params: { slug } }))
  return {
    paths,
    fallback: false,
  }
}
