import * as fs from 'fs'
import * as path from 'path'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import matter from 'gray-matter'
import remark from 'remark'
import html from 'remark-html'
import { COMMON_PLUGINS } from '../lib/remark'

type AboutProps = {
  data: {
    title: string
    content: string
  }
}

export default function About({ data }: AboutProps) {
  return (
    <>
      <Head>
        <title>RayGesualdo.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{data.title}</h1>

      <div dangerouslySetInnerHTML={{ __html: data.content }} />
    </>
  )
}

export const getStaticProps: GetStaticProps<AboutProps> = async (context) => {
  const MARKDOWN_PATH = path.join(process.cwd(), 'content/pages/about.md')
  const fileContents = fs.readFileSync(MARKDOWN_PATH, 'utf-8')
  const matterResult = matter(fileContents)
  const processedContent = await remark()
    .use(COMMON_PLUGINS)
    .use(html)
    .process(matterResult.content)
  const contentHtml = processedContent.toString()

  return {
    props: {
      data: {
        title: matterResult.data.title,
        content: contentHtml,
      },
    },
  }
}
