import { GetStaticProps } from 'next'
import Head from 'next/head'
import { getPathIds, getPostData, PostData } from '../lib/posts'

type HomeProps = {
  data: PostData[]
}

export default function Home({ data }: HomeProps) {
  return (
    <div>
      <Head>
        <title>RayGesualdo.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>RayGesualdo.com</h1>

      {data.map((post) => {
        const { year, month, day, slug, category } = post

        return (
          <div key={slug}>
            <h2>
              <a href={`/posts/${year}/${month}/${day}/${slug}`}>
                {post.title}
              </a>
            </h2>
            <small>{post.date}</small> | {Math.ceil(post.readingTime?.minutes)}{' '}
            Minute Read{' '}
            {category && (
              <span>
                | Category:{' '}
                <a href={`/category/${post.category!.slug}`}>
                  {post.category!.name}
                </a>
              </span>
            )}
            <p>{post.excerpt}</p>
          </div>
        )
      })}
    </div>
  )
}

export const getStaticProps: GetStaticProps<HomeProps> = async (context) => {
  const paths = getPathIds().reverse()
  const data = await Promise.all(
    paths.map((path) => getPostData(path.params.slug))
  )
  return {
    props: {
      data,
    },
  }
}
