name: Bust content cache

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'content/posts/**'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        env:
          WRITE_TRACKER_API_KEY: ${{ secrets.WRITE_TRACKER_API_KEY }}
        run: |
          curl --silent --show-error --fail "https://didraywritethisweek.raygesualdo.com/api/clear-cache?apiKey=$WRITE_TRACKER_API_KEY"
